# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: c5aac67782ab6aa9f7ed7f839b12ca8e9960f891e70ea8a0197d6c778423aa9564066812f9cb8f98c57efd65f6a22cb1c2100e084824d98c5de707cc47696b13
  facebook:
    app_id: 824862820905114
    app_secret: 495c92ed733fa4e74867ea006b3ca9b5
  google:
    client_id: 717126055406-hu7g6r3lfd8e4iis8d56vr2g0986s0ba.apps.googleusercontent.com
    client_secret: Md81RuJNXpvCtOhg5rcVzz70
  github:
    client_id: 670cb57dcfd16dd61072
    client_secret: a24d3a558d7ffbb8ea0ec40626ca6b1609f2941f

test:
  secret_key_base: <%%= ENV["SECRET_KEY_BASE"] %>
  facebook:
    app_id: 1
    app_secret: 1
  google:
    client_id: 1
    client_secret: 1
  github:
    client_id: 1
    client_secret: 1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook:
    app_id: <%= ENV["fb_id"] %>
    app_secret: <%= ENV["fb_secret"] %>
  google:
    client_id: <%= ENV["go_id"] %>
    client_secret: <%= ENV["go_secret"] %>
  github:
    client_id: <%= ENV["gh_id"] %>
    client_secret: <%= ENV["gh_secret"] %>
  smtp:
    user: <%= ENV["mail_user"] %>
    password: <%= ENV["mail_password"] %>